Basic docs
PaddlePaddle/PARL pull request #103
Opened 2019-07-29 08:42 UTC by TomorrowIsAnOtherDay

add documentation for basic classes: 
- parl.Model
- parl.Algorithm
- parl.Agent

2019-07-29 09:06 UTC, zenghsh3 commented on parl/core/fluid/algorithm.py
> +    Pulich Functions:
Publish

2019-07-29 09:12 UTC, fuyw commented on parl/core/fluid/agent.py
> +            c. build various programs(e.g., learn_program, predict_program) with data layers defined in step b.
c. Build ...

2019-07-29 09:13 UTC, fuyw commented on parl/core/fluid/agent.py
> +    | Agent is one of three basic classes of PARL.
one of the three ...

2019-07-29 09:16 UTC, fuyw commented on parl/core/fluid/agent.py
> +      This class will automatically initialize all the parameters of neural network, and provides an executor for users to run programs(self.fluid_executor).
This class will initialize the neural network parameters automatically, and provides an executor for users to run the programs (self.fluid_executor).

2019-07-29 09:19 UTC, fuyw commented on parl/core/fluid/agent.py
> +        - ``set_weights``: returns a list containing all the parameters of self.alg.
return ... ( for consistency )

2019-07-29 09:19 UTC, fuyw commented on parl/core/fluid/agent.py
> +        - ``predict``: return a action given current observation.
an action

2019-07-29 09:21 UTC, fuyw commented on parl/core/fluid/algorithm.py
> +        - ``predict``: return a action given current observation.
an action

2019-07-29 09:23 UTC, fuyw commented on parl/core/fluid/agent.py
> +        """return an action with noise when given the observation of the environment.
Return

2019-07-29 09:24 UTC, fuyw commented on parl/core/fluid/algorithm.py
> +    | ``Algorithm`` defines the way how to update the parameters of the ``Model``. That is, we define loss functions and the optimizer of the neural network. An ``Algorithm`` has at least a model.
This is where we define ...

2019-07-29 09:28 UTC, fuyw commented on parl/core/fluid/model.py
> +    | ``Model`` is a base class of PARL for the neural network. A ``Model`` is usually a policy or Q-value function, and predicts an action or an estimate according to the environmental observation.
or Q-value function, which predicts

2019-07-29 09:29 UTC, fuyw commented on parl/core/fluid/model.py
> +        - ``sync_weights_to``: Synchronize parameters of the current model to another model.
synchronize ...

2019-07-29 09:33 UTC, fuyw commented on parl/core/fluid/model.py
> +        """ returns a list containing all the parameters of current model.
Return a list

2019-07-29 09:54 UTC, TomorrowIsAnOtherDay commented on parl/core/fluid/algorithm.py
> +    Pulich Functions:
done

2019-07-29 09:54 UTC, TomorrowIsAnOtherDay commented on parl/core/fluid/agent.py
> +    | Agent is one of three basic classes of PARL.
done

2019-07-30 03:03 UTC, zenghsh3 commented on parl/core/fluid/agent.py
> +        - ``set_weights``: return a list containing all the parameters of self.alg.
comments of `set_weights` and `get_weights` are misplaced.
And `get_weights` will return a dict.

2019-07-30 03:10 UTC, zenghsh3 commented on parl/core/fluid/algorithm.py
> +    Pulish Functions:
Public

2019-07-30 03:15 UTC, zenghsh3 requested changes

2019-07-30 03:15 UTC, zenghsh3 commented on parl/core/fluid/algorithm.py
> +        - ``get_weights``: return a list containing all the parameters of the current model.
get_weights will return a dict: {model_attribute_name: list}.

2019-07-30 04:35 UTC, TomorrowIsAnOtherDay commented on parl/core/fluid/algorithm.py
> +    Pulish Functions:
done

2019-07-30 04:35 UTC, TomorrowIsAnOtherDay commented on parl/core/fluid/algorithm.py
> +        - ``get_weights``: return a list containing all the parameters of the current model.
done

2019-07-30 05:18 UTC, zenghsh3 submitted a review, later dismissed
LGTM

2019-07-30 06:05 UTC, zenghsh3 approved these changes

2019-07-30 06:05 UTC, merged