GPU卡接入资源池 #1037
PaddlePaddle/PARL pull request #1041
Opened 2023-02-09 09:53 UTC by zhengyuhong

# message.py
1. InitializedJob 新增gpus成员变量，在JobCenter给Client分配Job时，由JobCenter记录当前Job挂载的GPU卡ID列表（CPU场景ID列表为空）
2. InitializedWorker 初始化参数新增gpu_num，当前gpu_num > 0时，表示当前Worker所在机器的第0块GPU,第1块GPU,....,第gpu_num块GPU给Worker接入GPU集群，如果该机器保留部分GPU卡不接入GPU集群，请保留高位ID的GPU。
# status.py
1. WorkerStatus 新增gpu_num成员变量，记录当前Worker可用的GPU信息。
# start.py
1. 增加Master、Worker、Monitor的启动参数，xpu, gpu_num，xpu=cpu时用于启动CPU集群，cpu_num指定接入CPU集群的CPU个数，xpu=gpu时用于启动GPU集群，gpu_num指定接入GPU机器的GPU个数
cluster_monitor.py
1. 增加返回GPU使用情况的信息。
# worker.py
1. Worker 初始化参数新增gpu_num，默认值为0，取xpu_num=max(gpu_num, cpu_num)，使用xpu_num来初始化xpu_num个InitializedJob。当初始化参数gpu_num=None时，表示Worker自动读取GPU卡总数为gpu_num。
2. 当self.gpu_num > 0时，_get_worker_status返回Worker所在机器的GPU显存使用情况。
# monitor.py
1. 使用GPU场景，当启动参数xpu=gpu时，读取对应的html文件。
2. /cluster接口增加返回各个Worker的gpu显存使用情况。
# job_center.py
1. JobCenter 初始化参数增加xpu，用于区分GPU、CPU场景
2. 新增成员属性worker_vacant_gpus记录当前各个Worker待分配的GPU信息。
3. 新增成员属性worker_used_gpus记录当前各个Worker已分配的GPU信息。
4. request_job增加n_gpus参数，默认值为0，当n_gpus > 0时，则申请至少还有n_gpus个GPU的Worker上的Job，JobCenter将分配的GPU卡ID列表绑定到Job上。并更新worker_vacant_gpus、worker_used_gpus。
# master.py
1. Master 初始化参数增加xpu，用于区分GPU、CPU场景。
2. 在Client提交Job申请时，即tag == remote_constants.CLIENT_SUBMIT_TAG分支，判断Client申请的资源是否与当前资源（GPU/CPU）对应，如果不对应则返回remote_constants.REJECT_TAG。
3. 在Client提交GPU Job申请时，从zmq请求中提取n_gpus信息，转发给JobCenter.request_job(n_gpus)，由JobCenter判断是否满足，如果JobCenter返回返回InitialilzedJob对象。
4. 无论时Client提交CPU Job还是GPU Job，现在给Client返回的响应中均改为[remote_constants.NORMAL_TAG, cloudpickle.dumps(job)]，其中job为JobCenter返回InitialilzedJob对象。Client使用cloudpickle.loads获取InitialilzedJob对象，提取想要的信息，如GPU场景，需要从InitialilzedJob对象获取gpus成员变量，由JobCenter记录当前Job挂载的GPU卡ID列表。
# client.py
1. submit_job 增加参数n_gpus，当n_gpus > 0时，增加GPU Job申请场景，将n_gpus通过请求传递给Master，当没有空闲GPU，则休眠5s再申请，最多重试60次。
2. 由上面master.py第4点Client申请Job返回值发现变化，因此需要适配InitialilzedJob类型的返回值，从InitialilzedJob对象提取所需信息。
remote_wrapper.py
1. RemoteWrapper新增request_gpu_resource成员函数
2. 向InitialilzedJob.job_address提交remote_constants.INIT_OBJECT_TAG请求时，追加CUDA_VISIBLE_DEVICES=','.join(InitialilzedJob.gpus)的xparl_reserved_kwargs信息。
# job.py
1. 解析RemoteWrapper追加的xparl_reserved_kwargs信息，设置在初始化OBJ前设置环境变量os.environ["CUDA_VISIBLE_DEVICES"] = ...
remote_decorator.py
1. 将修饰符的n_gpus参数传递给RemoteWrapper，RemoteWrapper._n_gpus = n_gpus

2023-02-09 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=1041) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=1041) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PARL?pullRequest=1041) it.</sub>

2023-02-12 16:20 UTC, TomorrowIsAnOtherDay commented
@zhengyuhong 请新增单元测试校验新增功能的有效性。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +    def __init__(self, port, monitor_port=None, xpu='cpu'):
我司的昆仑芯片简称是xpu，不建议使用xpu作为变量名。
可以参考深度学习框架使用device表示硬件类型。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
> +        """Return vacant gpu number of a worker."""
缺乏类似186行的逻辑。如果目前是CPU集群，这里直接返回0即可。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
> +                                   worker has.
注释缺乏worker_vacant_gpus的说明。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
> +                                   worker has.
建议增加下key/value的说明。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
> +            if n_gpus > 0:
这部分的逻辑对于CPU/GPU处理不一样，看起来有点费劲。
GPU部分还是OK的，通过job去分配空闲GPU，而CPU部分就只有job的分配了，我们可以线下讨论下。marked。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +    def submit_job(self, max_memory, n_gpus, proxy_wrapper_nowait_object):
n_gpus -> n_gpu

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +                if not max_memory and n_gpus > 0:
max_memory 不是仅针对CPU模式的，在GPU模式中也需要考虑该限制。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/cluster_monitor.py
>          }
关于work_status，是否可考虑先定义一个基础类，然后通过继承得到CPU/GPU的类来维护？

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +                                assert (torch.cuda.device_count() == len(value.split(',')))
建议先判断条件是否满足，然后输出错误log然后raise异常，以帮助定位问题。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/start.py
> +    parser.add_argument('--gpu_ids', default='', type=str)
建议更名为--gpu.
help='comma separated list of GPU(s) to use. Default to use all available GPUs'

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/start.py
> +    parser.add_argument('--xpu', default='cpu', type=str, help='cpu/gpu')
如上，这个变量可以考虑去掉。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker.py
> +            error_message = "[Worker] has {} CPUs, {} GPUs, is rejected".format(self.cpu_num, self.gpu_num)
这里应该指出用户正在连接CPU到GPU集群，这是不允许的。反之亦然。目前的log没get到是这个意思。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker.py
> +            "vacant_gpu_memory": vacant_gpu_memory,
这里应返回每个GPU的显存信息。至于前端展示，可以等后续泽武协调人力支持。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +@click.option(
gpu_ids -> gpu.

help='comma separated list of GPU(s) to use. Default to use all available GPUs'

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/start.py
> +        master = Master(port, monitor_port, args.xpu)
master 不需要指定xpu？可以等第一个worker接进来后，再确认自己属于gpu还是cpu集群。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_wrapper.py
> +    def request_cpu_resource(self, global_client, max_memory, actor_ref_monitor):
request_cpu_resource / request_cpu_resource 这两个函数可以合成一个？

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +@click.option("--xpu", help="cpu for CPUs cluster, gpu for GPUs cluster.", default='cpu', type=str)
如刚才沟通，默认CPU，然后增加一个set true的变量来更改GPU。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +    "--gpu_ids", help="Set CUDA_VISIBLE_DEVICES manually. If not set, it will be empty string", default="", type=str)
gpu_ids -> gpu.

help='comma separated list of GPU(s) to use. Default to use all available GPUs'

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_wrapper.py
> +            cloudpickle.dumps(xparl_reserved_kwargs),
这个传输方案建议改成走max_memory类似的逻辑。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/message.py
> +      gpu_ids (str): id list of gpu to be used on the worker.
gpu_ids -> gpu

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
>      def get_total_cpu(self, worker_address):
这里查询CPU信息，直接反馈job的信息是OK的。但是感觉与gpu部分的逻辑不一致，建议新增变量单独维护CPU的信息。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/job_center.py
> +    def __init__(self, master_ip, xpu=remote_constants.CPU):
建议区分job/GPU/CPU。现在job和CPU混搭了。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +                    logger.info("A new worker {} is added, ".format(worker_address) +
这两行log可以merge？ 一起显示有多少CPU/多少GPU。

2023-02-20 03:56 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +            elif self.xpu == remote_constants.CPU:
这两部分的代码重叠过多，建议合并，统一从job_center request job就好，通过制定n_gpu来判定到底申请的是什么资源。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay requested changes

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +            n_gpu (int): Number of GPUs can be used by each remote instance.
Number of GPUs can used in this remote instance.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +                job = self.worker_manager.request_job(n_cpu=n_cpu, n_gpu=n_gpu)
job-> job_info
直接命名job不确定具体指代什么。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +                    job = cloudpickle.loads(message[1])
job->job_info

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +                    error_message = "[Client] connects to a CPUs Master."
[Client] Request fails. It is not allowed to request CPU resource from a GPU cluster.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +                    error_message = "[Client] connects to a GPUs Master."
[Client] Request fails. It is not allowed to request GPU resource from a CPU cluster.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +os.environ.pop('CUDA_VISIBLE_DEVICES', None)
这行代码应该保持原样。对于CPU集群，我们不希望默认使用GPU。如不清楚可线下当面沟通。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +    assert os.environ['PARL_BACKEND'] not in sys.modules, "{} imported".format(os.environ['PARL_BACKEND'])
{} is expected to be imported here.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/tests/gpu/cluster_test.py
> +@parl.remote_class(n_gpus=1)
n_gpus->n_gpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_wrapper.py
> +        n_gpu = kwargs.get('_xparl_remote_class_n_gpus', 0)
n_gpus -> n_gpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +            gpu (str): id list of GPUs can be used by each remote instance.
by this remote instance.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +                        del os.environ['XPARL_igonre_core']
del 这个变量后，得通过importlib reload 下parl，不然parl的算法库没法被使用。

-------------

Todo，增加单测补充actor里面包含parl.Model @TomorrowIsAnOtherDay

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +                    if 'PARL_BACKEND' in os.environ and os.environ['PARL_BACKEND'] != '':
这部分逻辑有问题。PARL_BACKEND这个环境变量很少设定，主要是解决两个框架都安装的情况下，用户可手动指定要用的变量。不能通过这个变量识别要用的框架。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +        worker_manager (WorkerManager): A thread-safe data structure that stores jobs,cpus,gpus about worker
A thread-safe data structure used to respond to resource request, maintaining the available computation resources in each worker.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    """The WorkerManager deals with everything related to workers.
A thread-safe data structure used to respond to resource request, maintaining the available computation resources in each worker.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """"Return vacant job number."""
Return the number of vacant jobs.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """"Return vacant cpu number."""
Return the number of vacant CPUs.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def gpu_num(self):
Return the number of vacant GPUs.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """Return connected worker number."""
Return the number of workers connected to the master node.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """Add jobs, cpus, gpus from JobCenter when a worker connects.
这个注释得重写。目前没有JobCenter的抽象了。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +            if not success:
如果失败，也打一部分log提示下原因。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def drop_worker(self, worker_address):
drop_worker->remove_worker.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +            worker (InitializedWorker): New worker with initialized job.
New worker with initialized jobs and CPU/GPU information.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def __init__(self, master_ip, devices=[remote_constants.CPU]):
这里应该assert一下devices是CPU or GPU，确保下devices的传参正确性。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +            error_message = "[WorkerCenter] without GPU device rejects a worker with GPUs"
The GPU cluster is allowed to accept a worker with CPU resources.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +            error_message = "[WorkerCenter] without CPU device rejects a worker with CPUs"
The CPU cluster is allowed to accept a worker with GPU resources.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        master_ip (str): IP address of the master node.
这里维护master_ip的用途是？我没看到哪里有引用这个成员变量，只看到在97行有更新这个变量。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def release(self, killed_job):
release->remove_job

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def filter(self, n_cpu, n_gpu):
增加注释。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def acquire(self, worker_address, n_cpu, n_gpu):
增加注释。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """Return total gpu number of a worker."""
Return the number of GPUs in the worker given its address.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """Return total cpu number of a worker."""
Return the number of CPUs in the worker given its address.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +        """Return vacant cpu number of a worker."""
Return the number of vacant CPUs in the worker given its address.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def get_vacant_gpu(self, worker_address):
Return the number of vacant GPUs in the worker given its address.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +    def reset_job(self, job):
这个函数的用途是？除了在parl/remote/tests/worker_manager_test.py测试中用到以外，没看到调用。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/worker_manager.py
> +            candidates = self.filter(n_cpu, n_gpu)
如果没有合适的candidates，这里得输出log。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +    """The cpu center deals with everything related to allocation for CPUs.
Record CPU information in each worker and respond to resource allocation of CPUs.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +    def acquire(self, worker_address, n_cpu):
acquire->allocate

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +        """acquire n_cpu CPUs on worker_address
allocate n_cpu CPUs from the worker

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +    def release(self, worker_address, initialized_cpu):
release->recycle

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +        """Return vacant cpu number of a worker."""
Return the number of vacant CPUs in the worker.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +        """"Return vacant cpu number."""
Return the number vacant of CPUs of all the workers

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/cpu_resource.py
> +        """Return total cpu number of a worker."""
Return the number of CPUs of all the workers

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/gpu_resource.py
> +    """The gpu center deals with everything related to allocation for GPUs.
Record GPU information in each worker and respond to resource allocation of GPUs.

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/gpu_resource.py
> +    def drop_gpu(self, worker_address):
drop->remove

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/gpu_resource.py
> +    def acquire(self, worker_address, n_gpu):
acquire->allocate

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/gpu_resource.py
> +    def release(self, worker_address, initialized_gpu):
release->recycle

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/message.py
> +        self.initialized_cpu = None  # Record CPU(s) used in a job
initialized_cpu -> allocated_cpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/message.py
> +        self.initialized_gpu = None  # Record GPU(s) used in a job
initialized_gpu -> allocated_gpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_wrapper.py
> +            job = self.request_resource(self.GLOBAL_CLIENT, max_memory, n_gpu)
job->job_info

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_wrapper.py
> +            job = global_client.submit_job(max_memory, n_gpu)
job->job_info

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/start.py
> +    parser.add_argument('--gpu_cluster', default=False, type=bool)
这个传参数不够优雅。建议改成--gpu_cluster ，那就启动GPU集群，否则默认不启动。

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/message.py
> +class InitializedGpu(object):
initialized_cpu -> allocated_cpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/message.py
> +class InitializedCpu(object):
initialized_cpu -> allocated_cpu

2023-02-22 09:44 UTC, TomorrowIsAnOtherDay commented on parl/remote/monitor.py
> +    parser.add_argument('--gpu_cluster', default=False, type=bool)
这个也要修改下设置方式。

2023-02-23 07:38 UTC, sanwushuosi commented on parl/remote/master.py
> +            reject = reject | (self.xpu == 'gpu' and message[1] == remote_constants.CPU_JOB)
建议221和222这两行写得浅显一点，否则以后改代码的人会很容易把逻辑给改错了。

2023-03-06 12:30 UTC, rical730 approved these changes

2023-03-06 13:04 UTC, TomorrowIsAnOtherDay approved these changes
LTGM. Thank you all guys!

2023-03-06 13:07 UTC, merged