fix css max-width bug
PaddlePaddle/PARL pull request #134
Opened 2019-08-14 12:27 UTC by fuyw

2019-08-14 23:42 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +        xparl start --port localhost:1234 --monitor_port 5005
We should not mention monitor_port here. The usage here should be as compact as possible. Please add monitor_port at our documentation.

2019-08-14 23:42 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +    master node. And a cluster monitor is start at `localhost:5005` to
Remove detail about the monitor here.

2019-08-14 23:42 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +    "--monitor_port", help="The port to start cluster monitor", type=str)
The port to start a cluster monitor

2019-08-15 16:02 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/features.rst
> +Features
rename this file to overview.rst.

2019-08-15 16:02 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/features.rst
> +Advantages
Advantages----> Why PARL

2019-08-15 16:03 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/features.rst
> + `xparl status` command to visualize the details of our cluster status,
`xparl status` -> \`\`xparl status``

2019-08-15 16:06 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/features.rst
> +Convenient visualization
Computation Resources Monitor.
PARL provides a web monitor to watch the status of any resources connected to the cluster.

2019-08-15 16:06 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/features.rst
> + paths. When any error happens, user can soon locate the bugs.
file executable paths  -> the path of each task.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay requested changes

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_decorator.py
> +                            MB and default value is none.
default value is none(unlimited).

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_decorator.py
> +        @remote_class(max_memory=300)
parl.remote_class(max_memroy=300)

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_decorator.py
> +        # Set maximum memory usage for each object
Set maximum memory usage to 300 MB for each object.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +            max_memory (float): Max memory (MB) can be used by this job process.
Maximum memory (MB) can be used by each remote instance.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +            # If you want to monitor cluster status, visit: http://{}
monitor -> check

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +##########
Remove this subtitle

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +========
Replace Features with Summary.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +Computation resources monitor
Web UI for computation resources

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +| PARL provides a web monitor to watch the status of any resources connected
PARL provides a web monitor to watch the status of any resources connected
 to the cluster. We can use ``xparl status`` command to visualize the details
 of our cluster status, including cpu usage, memory usage, average cpu loads
 and the path of each task. When any error happens, user can soon locate the bugs.

-----

 PARL provides a web monitor to watch the status of any resources connected
 to the cluster. Users can view the cluster status at a WEB UI. It shows the detailed information for each worker(e.g, memory used) and each task submitted.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +| PARL is compatible with any other frameworks, like tensorflow, pytorch or
Our framework for distributed training is compatible with ...

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/cluster_monitor.py
> +    def get_status_info(self):
Can you add a test script for this part of code?

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +        """Return current memory usage of the job process."""
Check if the memory used by this job exceeds `self.max_memory`

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +        stop_job = 'False'
Why don't you use False(bool) here ?

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/master.py
> +        elif tag == remote_constants.STATUS_TAG:
Please add a script testing this part of code.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/remote_decorator.py
> +        max_memory = None
Please remove this line.

2019-08-20 03:24 UTC, TomorrowIsAnOtherDay commented on parl/remote/scripts.py
> +            # If you want to monitor cluster status, visit: http://{}
visit -> view

2019-08-20 03:33 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +Simple usage
Easy-to-use

2019-08-20 03:35 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> + can be found in figure (b).
With the same implementation in IMPALA, PARL achieved an increase of 160% on data throughout over Ray(RLlib).

2019-08-20 03:36 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +| Unlike other parallel framework like Ray, which fails to import modules from
pls remove `like Ray`.  It seems a bit aggressive.

2019-08-20 05:15 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
> +| With a single `@parl.remote_class` decorator, we can access cluster's remote
With a single `@parl.remote_class` decorator, users can implement parallel training easily, and  not having to care about stuff of multi-processes, network communication.

2019-08-20 05:24 UTC, fuyw commented on parl/remote/cluster_monitor.py
> +    def get_status_info(self):
We already have one in tests/remote_monitor_test_x.py

2019-08-20 05:26 UTC, fuyw commented on parl/remote/job.py
> +        stop_job = 'False'
This `stop_job` flag will be sent to client, and zmq socket only receive a byte like this `to_byte(str(Fasle))`

2019-08-20 05:30 UTC, TomorrowIsAnOtherDay commented on parl/remote/job.py
> +        stop_job = 'False'
Yes, I know that only byte can be sent through ZMQ, but it's curious to return a string representing the test result. You may return a bool here and transfer it into a string before sending it out.

2019-08-21 02:18 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
>   to the cluster. We can use ``xparl status`` command to visualize the details
We can **also** use

2019-08-21 02:19 UTC, TomorrowIsAnOtherDay commented on docs/parallel_training/overview.rst
>   external files. PARL will automatically package all related files and send
files. -> file,

2019-08-21 02:21 UTC, TomorrowIsAnOtherDay commented on parl/remote/client.py
> +                if to_str(job_message[1]) == 'True':
It's hard to maintain the code written in this way. You should define a variable representing the meaning of `job_message[1]` and then check whether it is `True`.

2019-08-21 02:57 UTC, TomorrowIsAnOtherDay approved these changes

2019-08-21 03:32 UTC, merged