NeurIPS RL papers
PaddlePaddle/PARL pull request #184
Opened 2019-12-09 15:26 UTC by TomorrowIsAnOtherDay

![image](https://user-images.githubusercontent.com/25046619/70448345-30f8e780-1adb-11ea-9389-94e8b5d3659f.png)
The new article in our zhihu blog details the RL paper in NeurIPS 2019. So I upload this table recording all the RL papers in our repository.

2019-12-09 15:27 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=184) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PARL?pullRequest=184) it.</sub>

2019-12-10 02:12 UTC, zenghsh3 requested changes
Github cannot render number format, can you export it to the csv format?

2019-12-11 07:14 UTC, TomorrowIsAnOtherDay commented
I'm not sure whether it can render csv files. Have you tried csv files before?

2019-12-11 07:20 UTC, zenghsh3 approved these changes

2019-12-11 07:21 UTC, merged