add simple dqn demo
PaddlePaddle/PARL pull request #254
Opened 2020-04-27 05:10 UTC by Banmahhhh

2020-04-27 07:12 UTC, rical730 commented on examples/DQN/README.md
>  # To train a model for Pong game
please remove this line

2020-04-27 07:12 UTC, rical730 commented on examples/DQN/README.md
>  > To train more games, you can install more rom files from [here](https://github.com/openai/atari-py/tree/master/atari_py/atari_roms).
please remove this line

2020-04-27 07:12 UTC, rical730 commented on examples/DQN/train.py
> +from model import Model
maybe it will be better to rename model to cartpole_model, and rename Model to CartpoleModel.

2020-04-27 07:12 UTC, rical730 commented on examples/DQN/train.py
> +from agent import Agent
maybe it will be better to rename agent to cartpole_agent, and rename Agent to CartpoleAgent

2020-04-27 07:12 UTC, rical730 commented on examples/DQN/train.py
> +            writer.add_scalar('loss', train_loss, agent.global_step)
duplicated with last line

2020-04-28 03:00 UTC, TomorrowIsAnOtherDay requested changes

2020-04-28 03:00 UTC, TomorrowIsAnOtherDay commented on examples/DQN/train.py
> +    return statistics.mean(eval_reward)
why don't we use np.mean here?

2020-04-28 03:00 UTC, TomorrowIsAnOtherDay commented on examples/DQN/train.py
> +        print('episode:{}    test_reward:{}'.format(episode, eval_reward))
please use logger.info here.(from parl.utils import logger)

2020-04-28 03:37 UTC, TomorrowIsAnOtherDay submitted a review, later dismissed
Looks good to me.

2020-04-28 05:29 UTC, TomorrowIsAnOtherDay approved these changes

2020-04-28 05:29 UTC, merged