Add Prioritized DQN
PaddlePaddle/PARL pull request #326
Opened 2020-07-01 11:03 UTC by tanzeyy

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay requested changes

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/test_per.py
> +#   Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
All the test files' name must be end with `_test.py`

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/README.md
> +Prioritized experience replay (PER) develops a framework for prioritizing experience, so as to replay important transitions more frequently. In original paper, the authors define the probability of s
Generally, in README.md, we show the link to the paper and describe the performance of algorithm. Please rewrite this file. Here is an [example](https://github.com/PaddlePaddle/PARL/tree/9444470c1f92f653e5e0c0d19c3bf44bc1cea665/examples/DQN_variant).

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/atari/agent.py
> +        lr = 0.00025 / 4
When using a stable learning rate, we should put the definition of learning rate in algorithm. Please refer to the lr in PolicyGradient.
https://github.com/PaddlePaddle/PARL/blob/a50793e43acdbf5c27d5fd96bcec8b76dc777c0d/parl/algorithms/fluid/policy_gradient.py#L26

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/atari/alg.py
> +        optimizer = fluid.optimizer.SGD(learning_rate=learning_rate)
Why do we use SGD here? Adam is a faster optimizer in general.

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/atari/agent.py
> +    def learn(self, obs, act, reward, next_obs, terminal, ISweight):
Please name the arguments using the same style. IsWeight -> sample_weight.

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/atari/alg.py
> +class PrioritizedDQN(parl.Algorithm):
Please put the file to the algorithm folder so that users can import it from parl.algorithm.
folder: parl/algorithms/fluid

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/train.py
> +    parser.add_argument(
Please remove the argument.

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/train.py
> +    logger.set_dir(log_dir)
just use `auto_set_dir()` here.

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/README.md
> +training and evaluation curves will be saved in `./exps/run_train`, which can viewed with:
Please remove the block as PARL doesn't support visualdl at every platform(only at linux with python3.6+).

2020-07-01 13:55 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/per/proportional.py
> +    @_check_full
Please remove the decorator here. We are writing examples for the users. We have to reduce the bar to understand the code. A decorator can make the code cooler, but harder to understand.

2020-07-02 02:19 UTC, zenghsh3 requested changes

2020-07-02 02:19 UTC, zenghsh3 commented on examples/Prioritized_DQN/per/baselines/replay_memory.py
> +# Third party code
`baselines` directory is not used, please remove it.

2020-07-02 11:14 UTC, tanzeyy commented
Modified as required, experiment results on atari environment will be added when finished.

2020-07-03 02:48 UTC, zenghsh3 requested changes

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/README.md
> +<img src=".figs/prob.jpg" />
The size of these images may be too large, please reduce it.

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/atari/agent.py
> +        lr = self.alg.lr
It's redundant. Please don't feed the learning rate to the algorithm.

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/atari/alg.py
> +from parl.core.fluid.algorithm import Algorithm
Please remove this line, it's not used.

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/atari/alg.py
> +        # choose acc. to behavior network
The comment is not easy to understand. Please clarify it.

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/atari/alg.py
> +            layers.elementwise_mul(action_onehot, pred_value), dim=1)
Can we directly use `*` instead of `elementwise_mul`?

2020-07-03 02:48 UTC, zenghsh3 commented on examples/Prioritized_DQN/per/utils.py
> +    def _check_full(self):
The implementation is not compact, maybe can replace it with 
`assert self.elements.full(), "The replay memory is not full!"`

2020-07-24 02:05 UTC, TomorrowIsAnOtherDay commented on examples/Prioritized_DQN/proportional_per.py
> +class SumTree:
SumTree(object)

2020-07-24 02:30 UTC, zenghsh3 requested changes

2020-07-24 02:30 UTC, zenghsh3 commented on examples/Prioritized_DQN/README.md
> +Results have been reproduced on following three environments:
please specify the algorithm variant is dqn or double dqn.

2020-07-27 07:13 UTC, TomorrowIsAnOtherDay approved these changes
LGTM.

2020-07-27 07:15 UTC, zenghsh3 approved these changes
LGTM

2020-07-27 07:17 UTC, merged