add PPO example
PaddlePaddle/PARL pull request #39
Opened 2019-01-02 05:40 UTC by zenghsh3

- add PPO example
- refine DDPG code

2019-01-02 07:28 UTC, TomorrowIsAnOtherDay requested changes

2019-01-02 07:28 UTC, TomorrowIsAnOtherDay commented on parl/algorithms/ppo.py
> +        result1 = layers.elementwise_div(
variable names such as `result1` and `result2` seem ambiguous here, could you rename them to another names that has substantial meaning actually.

2019-01-02 07:28 UTC, TomorrowIsAnOtherDay commented on parl/algorithms/ppo.py
>      def define_policy_learn(self, obs, actions, advantages, beta=None):
`Beta` decides which way to approximate TRPO, could you add some comments here?

2019-01-02 07:28 UTC, TomorrowIsAnOtherDay commented on examples/DDPG/train.py
>          action = action * act_bound
This line has a prerequisite that the action bound is symmetric, I recommend you to use a linear transformation here to transform the `[-1, -1]` to  `[lower bound, upper bound]`

2019-01-02 07:28 UTC, TomorrowIsAnOtherDay commented on parl/algorithms/ppo.py
> +        self.old_policy_model = deepcopy(model.policy_model)
add some comments here, users may be curious at why there is copy of policy here

2019-01-03 16:34 UTC, zenghsh3 commented on parl/algorithms/ppo.py
> +        result1 = layers.elementwise_div(
done

2019-01-03 16:34 UTC, zenghsh3 commented on parl/algorithms/ppo.py
>      def define_policy_learn(self, obs, actions, advantages, beta=None):
done

2019-01-03 16:34 UTC, zenghsh3 commented on examples/DDPG/train.py
>          action = action * act_bound
done

2019-01-03 16:34 UTC, zenghsh3 commented on parl/algorithms/ppo.py
> +        self.old_policy_model = deepcopy(model.policy_model)
done

2019-01-04 02:26 UTC, TomorrowIsAnOtherDay approved these changes

2019-01-04 02:47 UTC, merged