Torch es
PaddlePaddle/PARL pull request #618
Opened 2021-05-06 14:21 UTC by wangzelong0663

Upgrade the interface of the ES of torch version.

2021-05-25 06:14 UTC, zenghsh3 requested changes

2021-05-25 06:14 UTC, zenghsh3 commented on benchmark/torch/ES/README.md
> +![learninng_curve](result_es.png)
Use the consistent drawing tools and use the training steps as the x-axis.

2021-06-01 06:14 UTC, zenghsh3 approved these changes, later dismissed
LGTM

2021-06-01 08:38 UTC, TomorrowIsAnOtherDay approved these changes

2021-06-01 08:38 UTC, merged