add torch based CQL
PaddlePaddle/PARL pull request #719
Opened 2021-09-29 08:41 UTC by rical730

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay requested changes

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/README.md
> ++ Mujoco games: Please see [here](https://github.com/openai/mujoco-py) to know more about Mujoco games.
games -> simulator.

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/README.md
> +## Reproduce CQL with PARL
We all know that offline-RL requires a dataset for training. However, I did not see any instruction about how to use the D4RL dataset in this example.

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/mujoco_agent.py
> +    def rad_sample(self, obs):
Where do you use this function?

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/train.py
> +def load_hdf5(dataset, rpm):
Can we move this function to the `ReplayMemory` class? 
I suppose that it would be used again in other offline-RL examples.

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/train.py
> +LAGRANGE_THRESH = 10  # but paper: 10.0 in mujoco,  5.0 in Franka kitchen and Adroit domains
but paper?

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on benchmark/torch/cql/train.py
> +LAGRANGE_THRESH = 10  # but paper: 10.0 in mujoco,  5.0 in Franka kitchen and Adroit domains
The default values for the hyperparameters should be defined in the algorithm implementation.  We can also add comments for them in the `__init__` function.

2021-10-12 06:18 UTC, TomorrowIsAnOtherDay commented on parl/algorithms/torch/cql.py
> +    def sync_target(self, decay=None):
Please add comment for this function.

2021-10-12 08:26 UTC, rical730 commented on benchmark/torch/cql/README.md
> +## Reproduce CQL with PARL
done

2021-10-12 08:26 UTC, rical730 commented on benchmark/torch/cql/README.md
> ++ Mujoco games: Please see [here](https://github.com/openai/mujoco-py) to know more about Mujoco games.
fixed

2021-10-12 08:26 UTC, rical730 commented on benchmark/torch/cql/mujoco_agent.py
> +    def rad_sample(self, obs):
Sorry for forgotten this function. It is used for debugging, will be removed.

2021-10-12 08:26 UTC, rical730 commented on benchmark/torch/cql/train.py
> +LAGRANGE_THRESH = 10  # but paper: 10.0 in mujoco,  5.0 in Franka kitchen and Adroit domains
typo fixed. Hyperparameter configuration will be simplified

2021-10-12 08:26 UTC, rical730 commented on benchmark/torch/cql/train.py
> +def load_hdf5(dataset, rpm):
done

2021-10-12 08:26 UTC, rical730 commented on parl/algorithms/torch/cql.py
> +    def sync_target(self, decay=None):
done

2021-10-12 08:49 UTC, TomorrowIsAnOtherDay commented on parl/utils/replay_memory.py
> +    def load_from_d4rl(self, dataset):
Please add comment for this function.

2021-10-13 05:13 UTC, rical730 commented on parl/utils/replay_memory.py
> +    def load_from_d4rl(self, dataset):
done

2021-10-13 06:42 UTC, TomorrowIsAnOtherDay commented on parl/utils/replay_memory.py
> +    def load_from_d4rl(self, dataset):
please add an example for this function.

2021-10-13 08:08 UTC, rical730 commented on parl/utils/replay_memory.py
> +    def load_from_d4rl(self, dataset):
finished

2021-10-13 08:38 UTC, TomorrowIsAnOtherDay commented on parl/utils/replay_memory.py
> +        Examples:
To make it readable in `read the docs`, please refer to this page:  https://github.com/PaddlePaddle/PARL/blob/93304b7b7150b0c0d72dd4b47bafc437fd9eeaea/parl/core/paddle/agent.py#L34

2021-10-14 07:07 UTC, rical730 commented on parl/utils/replay_memory.py
> +        Examples:
done

2021-10-14 07:13 UTC, TomorrowIsAnOtherDay approved these changes
LGTM.

2021-10-14 11:26 UTC, merged