Added CQL paddle version
PaddlePaddle/PARL pull request #744
Opened 2021-11-10 07:25 UTC by Jiukaishi

2021-11-10 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=744) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PARL?pullRequest=744) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PARL?pullRequest=744) it.</sub>

2021-11-10 07:42 UTC, zenghsh3 commented
@Jiukaishi You can fix code style issues by following the guide: https://github.com/PaddlePaddle/PARL/blob/96070194022fb044dd0be2c9e0a5ffc24b47212c/docs/zh_CN/Overview.md#%E4%BB%A3%E7%A0%81%E8%B4%A1%E7%8C%AE%E8%A7%84%E8%8C%83

2021-11-15 06:22 UTC, zenghsh3 requested changes

2021-11-15 06:22 UTC, zenghsh3 commented on examples/CQL/train.py
> +        closs, aloss = agent.learn(batch_obs, batch_action, batch_reward,
recommended naming: c_loss/critic_loss and a_loss/actor_loss

2021-11-15 06:22 UTC, zenghsh3 commented on parl/algorithms/paddle/cql.py
> +        self.sample_normal = Normal(loc=0., scale=1.)
It's unused, pls remove it.

2021-11-15 06:22 UTC, zenghsh3 commented on parl/algorithms/paddle/cql.py
> +        #self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
Pls remove these comments.

2021-11-15 06:22 UTC, zenghsh3 commented on parl/algorithms/paddle/cql.py
> +        )  #act_mean + self.sample_normal.sample(act_log_std.shape) * act_log_std.exp()
Pls remove these comments.

2021-11-15 06:22 UTC, zenghsh3 commented on parl/algorithms/paddle/cql.py
> +        # torch.FloatTensor(
Pls remove these comments.

2022-01-17 06:20 UTC, TomorrowIsAnOtherDay commented on examples/CQL/README.md
> +Different from Online RL which gather new data directly from the environment, Offline RL algorithms learn a policy or Q-function from static dataset, without additional interaction with the environme
Remove the sentence about the offline RL. We would like the reader to refer to the original paper for more introduction.

2022-01-17 06:20 UTC, TomorrowIsAnOtherDay commented on examples/CQL/README.md
> ++ [parl>2.0.2](https://github.com/PaddlePaddle/PARL)
\>=2.0.4

2022-01-17 06:20 UTC, TomorrowIsAnOtherDay commented on examples/CQL/README.md
> ++ D4RL datasets: Please see [here](https://sites.google.com/view/d4rl/home) to know more about D4RL datasets. D4RL require Mujoco as a dependency. For more D4RL usage methods, please refer to its [gu
The algorithm is tested in the [D4RL dataset](https://sites.google.com/view/d4rl/home), one of the most commonly used dataset for offline RL. For more details about D4RL usagage, please refer to [the page](https://github.com/rail-berkeley/d4rl#using-d4rl).

2022-01-17 06:20 UTC, TomorrowIsAnOtherDay commented on examples/CQL/README.md
> +![avatar](./result.png)
@zenghsh3 Please tell @Jiukaishi  how to upload the result image to the other repository.

2022-01-17 06:20 UTC, TomorrowIsAnOtherDay commented on parl/algorithms/paddle/cql.py
> +        # check_model_method(model, 'value', self.__class__.__name__)
Why do we comment these lines? 
I think they are necessary to reuse the algorithm?

2022-01-18 02:19 UTC, TomorrowIsAnOtherDay approved these changes
LGTM.

2022-01-18 02:20 UTC, zenghsh3 approved these changes
LGTM

2022-01-18 02:20 UTC, merged